const FILES="abcdefgh";
const glyph={wp:"♙",wn:"♘",wb:"♗",wr:"♖",wq:"♕",wk:"♔",bp:"♟",bn:"♞",bb:"♝",br:"♜",bq:"♛",bk:"♚"};
let S={board:[],turn:"w",castle:"KQkq",ep:-1,half:0,full:1},history=[],selected=-1,flipped=false,lastMove=null,moves=[],trainer=false;

const boardEl=document.querySelector("#board"),depth=document.querySelector("#depth");
function start(){S.board=Array(64).fill(null);const back=["r","n","b","q","k","b","n","r"];for(let x=0;x<8;x++){S.board[x]=`w${back[x]}`;S.board[8+x]="wp";S.board[48+x]="bp";S.board[56+x]=`b${back[x]}`;}draw();engine.init();}

function rc(i){return[Math.floor(i/8),i%8]} function ix(r,c){return r*8+c} function inside(r,c){return r>=0&&r<8&&c>=0&&c<8}
function color(p){return p?.[0]} function type(p){return p?.[1]}
function attacks(b,from,to){const p=b[from],t=type(p),[r,c]=rc(from),[R,C]=rc(to),dr=R-r,dc=C-c;if(!p)return false;if(t==="p")return color(p)==="w"?dr===1&&Math.abs(dc)===1:dr===-1&&Math.abs(dc)===1;if(t==="n")return[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]].some(([a,d])=>a===dr&&d===dc);if(t==="k")return Math.max(Math.abs(dr),Math.abs(dc))===1;if((t==="b"||t==="q")&&Math.abs(dr)===Math.abs(dc)||(t==="r"||t==="q")&&(dr===0||dc===0)){const sr=Math.sign(dr),sc=Math.sign(dc);let rr=r+sr,cc=c+sc;while(rr!==R||cc!==C){if(b[ix(rr,cc)])return false;rr+=sr;cc+=sc}return true}return false}
function squareAttacked(b,sq,by){for(let i=0;i<64;i++)if(color(b[i])===by&&attacks(b,i,sq))return true;return false}
function inCheck(b,col){const k=b.findIndex(p=>p===`${col}k`);return k<0||squareAttacked(b,k,col==="w"?"b":"w")}
function pseudo(s,from){const b=s.board,p=b[from],col=color(p),t=type(p),[r,c]=rc(from),out=[];if(!p)return out;const add=(R,C)=>{if(!inside(R,C))return;const to=ix(R,C);if(!b[to]||color(b[to])!==col)out.push({from,to,promotion:null})};
if(t==="p"){const d=col==="w"?1:-1,R=r+d;if(inside(R,c)&&!b[ix(R,c)]){out.push({from,to:ix(R,c),promotion:(R===0||R===7)?"q":null});if((col==="w"?r===1:r===6)&&!b[ix(r+2*d,c)])out.push({from,to:ix(r+2*d,c),promotion:null})}for(const dc of[-1,1]){const C=c+dc;if(!inside(R,C))continue;const to=ix(R,C);if((b[to]&&color(b[to])!==col)||to===s.ep)out.push({from,to,enpassant:to===s.ep,promotion:(R===0||R===7)?"q":null})}}
if(t==="n")for(const[a,d]of[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]])add(r+a,c+d);
if(t==="b"||t==="r"||t==="q"){const dirs=[];if(t==="b"||t==="q")dirs.push([1,1],[1,-1],[-1,1],[-1,-1]);if(t==="r"||t==="q")dirs.push([1,0],[-1,0],[0,1],[0,-1]);for(const[dR,dC]of dirs){let R=r+dR,C=c+dC;while(inside(R,C)){const to=ix(R,C);if(!b[to])out.push({from,to});else{if(color(b[to])!==col)out.push({from,to});break}R+=dR;C+=dC}}}
if(t==="k"){for(let dR=-1;dR<=1;dR++)for(let dC=-1;dC<=1;dC++)if(dR||dC)add(r+dR,c+dC);if(!inCheck(b,col)){const enemy=col==="w"?"b":"w",ks=col==="w"?"K":"k",qs=col==="w"?"Q":"q";if((col==="w"&&from===4)||(col==="b"&&from===60)){const rk=from+3,rq=from-4;if(s.castle.includes(ks)&&b[rk]===col+"r"&&!b[from+1]&&!b[from+2]&&!squareAttacked(b,from+1,enemy)&&!squareAttacked(b,from+2,enemy))out.push({from,to:from+2,castle:true});if(s.castle.includes(qs)&&b[rq]===col+"r"&&!b[from-1]&&!b[from-2]&&!b[from-3]&&!squareAttacked(b,from-1,enemy)&&!squareAttacked(b,from-2,enemy))out.push({from,to:from-2,castle:true})}}}return out}
function clone(s){return{board:[...s.board],turn:s.turn,castle:s.castle,ep:s.ep,half:s.half,full:s.full}}
function make(s,m){const n=clone(s),p=n.board[m.from],col=color(p),capt=n.board[m.to];n.board[m.to]=p;n.board[m.from]=null;if(m.enpassant)n.board[m.to+(col==="w"?-8:8)]=null;if(m.castle){const rf=m.to>m.from?m.from+3:m.from-4,rt=m.to>m.from?m.from+1:m.from-1;n.board[rt]=n.board[rf];n.board[rf]=null}if(m.promotion)n.board[m.to]=col+m.promotion;n.ep=-1;if(type(p)==="p"&&Math.abs(m.to-m.from)===16)n.ep=(m.to+m.from)/2;if(type(p)==="k")n.castle=n.castle.replace(col==="w"?/[KQ]/g:/[kq]/g,"");if(type(p)==="r"){if(m.from===0)n.castle=n.castle.replace("Q","");if(m.from===7)n.castle=n.castle.replace("K","");if(m.from===56)n.castle=n.castle.replace("q","");if(m.from===63)n.castle=n.castle.replace("k","")}if(capt==="wr"&&m.to===0)n.castle=n.castle.replace("Q","");if(capt==="wr"&&m.to===7)n.castle=n.castle.replace("K","");if(capt==="br"&&m.to===56)n.castle=n.castle.replace("q","");if(capt==="br"&&m.to===63)n.castle=n.castle.replace("k","");n.half=(type(p)==="p"||capt)?0:n.half+1;if(col==="b")n.full++;n.turn=col==="w"?"b":"w";return n}
function legal(s,from){return pseudo(s,from).filter(m=>!inCheck(make(s,m).board,color(s.board[from])))} function allLegal(s){let a=[];for(let i=0;i<64;i++)if(color(s.board[i])===s.turn)a.push(...legal(s,i));return a}
function san(m,before,after){const p=before.board[m.from],capture=!!before.board[m.to]||m.enpassant;let base=type(p)==="p"?(capture?FILES[rc(m.from)[1]]:""):type(p).toUpperCase();if(type(p)!=="p"){const same=allLegal(before).filter(x=>x.to===m.to&&x.from!==m.from&&type(before.board[x.from])===type(p));if(same.length)base+=FILES[rc(m.from)[1]]}if(capture)base+="x";base+=FILES[rc(m.to)[1]]+(8-rc(m.to)[0]);if(m.promotion)base+="=Q";if(m.castle)base=m.to>m.from?"O-O":"O-O-O";if(inCheck(after.board,after.turn))base+=allLegal(after).length?"+":"#";return base}
function move(m){const before=clone(S);S=make(S,m);history.push(before);lastMove=m;selected=-1;moves.push(san(m,before,S));draw();engine.analyze(fen(),Number(depth.value))}
function draw(){boardEl.innerHTML="";for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++){const r=flipped?rr:7-rr,c=flipped?7-cc:cc,i=ix(r,c),el=document.createElement("div");el.className="sq "+((r+c)%2?"dark":"light");if(lastMove&&(i===lastMove.from||i===lastMove.to))el.classList.add("last");if(i===selected)el.classList.add("selected");if(selected>=0&&legal(S,selected).some(m=>m.to===i))el.classList.add(S.board[i]?"capture":"legal");const rank=document.createElement("span");rank.className="coord rank";rank.textContent=8-r;const file=document.createElement("span");file.className="coord file";file.textContent=FILES[c];if(S.board[i]){const sp=document.createElement("span");sp.className="piece "+(color(S.board[i])==="w"?"white-piece":"black-piece");sp.textContent=glyph[S.board[i]];el.appendChild(sp)}el.append(rank,file);el.onclick=()=>clickSq(i);boardEl.appendChild(el)}document.querySelector("#turnLabel").textContent=(S.turn==="w"?"White":"Black")+" to move";const legalNow=allLegal(S);document.querySelector("#statusLabel").textContent=inCheck(S.board,S.turn)?(legalNow.length?"Check":"Checkmate"):(legalNow.length?"Ready":"Stalemate");document.querySelector("#moves").innerHTML=moves.map((m,i)=>`<div class="move"><b>${Math.floor(i/2)+1}${i%2?".":"..."}</b> ${m}</div>`).join("")}
function clickSq(i){if(selected<0){if(color(S.board[i])===S.turn){selected=i;draw()}return}const m=legal(S,selected).find(x=>x.to===i);if(m)move(m);else{selected=color(S.board[i])===S.turn?i:-1;draw()}}
function fen(){let rows=[];for(let r=7;r>=0;r--){let row="",empty=0;for(let c=0;c<8;c++){const p=S.board[ix(r,c)];if(!p)empty++;else{if(empty){row+=empty;empty=0}const q=type(p);row+=color(p)==="w"?q.toUpperCase():q}}if(empty)row+=empty;rows.push(row)}return rows.join("/")+" "+S.turn+" "+(S.castle||"-")+" "+(S.ep<0?"-":FILES[rc(S.ep)[1]]+(8-rc(S.ep)[0]))+" "+S.half+" "+S.full}

const engine={worker:null,ready:false,starting:false,searchId:0,init(){if(this.worker)return;this.starting=true;this.worker=new Worker("stockfish-worker.js");this.worker.onmessage=e=>this.onmsg(e.data);this.worker.onerror=()=>{this.starting=false;document.querySelector("#engineStatus").textContent="Engine error — retrying…";setTimeout(()=>this.restart(),700)};document.querySelector("#engineStatus").textContent="Loading Stockfish 19…";this.worker.postMessage("uci")},restart(){try{this.worker?.terminate()}catch{}this.worker=null;this.ready=false;this.starting=false;this.init()},onmsg(d){if(typeof d!=="string")return;if(d==="uciok"){this.worker.postMessage("setoption name Threads value 1");this.worker.postMessage("isready")}else if(d==="readyok"){this.ready=true;this.starting=false;document.querySelector("#engineStatus").textContent="Ready — Stockfish 19 lite";this.analyze(fen(),Number(depth.value))}else if(d.startsWith("info")&&d.includes(" score ")){const m=d.match(/score (cp|mate) (-?\d+)/),pv=d.match(/ pv (.+)$/);if(m){const v=m[1]==="mate"?Math.sign(Number(m[2]))*99:Math.max(-99,Math.min(99,Number(m[2])/100));document.querySelector("#evalText").textContent=m[1]==="mate"?"M"+m[2]:v.toFixed(2);document.querySelector("#evalFill").style.height=(50+Math.max(-50,Math.min(50,v*8)))+"%"}if(pv)document.querySelector("#bestMove").textContent=pv[1].split(" ")[0]}else if(d.startsWith("bestmove ")){document.querySelector("#engineStatus").textContent=this.ready?"Ready — search complete":"Ready"}else if(d.startsWith("error "))document.querySelector("#engineStatus").textContent=d.slice(6)},analyze(f,d){if(!this.ready)return;this.searchId++;this.worker.postMessage("stop");this.worker.postMessage("position fen "+f);this.worker.postMessage("go depth "+Math.max(8,Math.min(24,d||16)))}}};
document.querySelector("#resetBtn").onclick=()=>{history=[];moves=[];lastMove=null;try{engine.worker?.postMessage("ucinewgame")}catch{}start()};
document.querySelector("#undoBtn").onclick=()=>{if(history.length){S=history.pop();moves.pop();lastMove=null;draw();engine.analyze(fen(),Number(depth.value))}};
document.querySelector("#flipBtn").onclick=()=>{flipped=!flipped;draw()};
document.querySelector("#fenBtn").onclick=async()=>{await navigator.clipboard?.writeText(fen());document.querySelector("#statusLabel").textContent="FEN copied"};
document.querySelector("#analyzeBtn").onclick=()=>engine.analyze(fen(),Number(depth.value));
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");trainer=b.dataset.mode==="trainer";document.querySelector("#trainerPanel").hidden=!trainer;document.querySelector("#enginePanel").hidden=trainer});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=b.dataset.panel;document.querySelector("#enginePanel").hidden=p!=="engine";document.querySelector("#trainerPanel").hidden=p!=="trainer"});
document.querySelector("#trainerStart").onclick=()=>{trainer=true;document.querySelector("#trainerResult").textContent="Find the best move. Stockfish will analyze this position.";engine.analyze(fen(),Number(depth.value))};
let deferredInstall=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;document.querySelector("#installBtn").hidden=false});document.querySelector("#installBtn").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;document.querySelector("#installBtn").hidden=true};window.addEventListener("appinstalled",()=>document.querySelector("#installBtn").hidden=true);
start();